name: レビュワーが全て承認した場合に他のワークフローを実行

on:
  pull_request_review:
    branches:
      - 
    types: [submitted]

jobs:
  check-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Check if all reviews are approved
        id: check-reviews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pull_request_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          repository=$(jq --raw-output .repository.full_name "$GITHUB_EVENT_PATH")

          reviews=$(curl -s -H "Authorization: $GITHUB_TOKEN" "https://api.github.com/repos/$repository/pulls/$pull_request_number/reviews")
          review_count=$(echo "$reviews" | jq 'length')
          
          # レビュワーが設定されていない場合、終了
          if [ review_count -eq 0 ]; then
            echo 'No reviews found.'
            exit 1
          fi

          approved_review_count=$(echo "$reviews" | jq 'map(select(.state == "APPROVED")) | length')

          # 設定されたレビュワーが全て承認しているかチェック
          if [ $review_count -eq $approved_review_count ]; then
            echo 'All reviews are approved.'
            echo "::set-output name=all_reviews_approved::true"
          else
            echo 'Not all reviews are approved.'
            exit 1
          fi
      - name: check status
        if: steps.check-reviews.outputs.all_reviews_approved != 'true'
        run: exit 1
      - name: success
        run: |
          echo ":クラッカー: The job was automatically triggered by a ${{ github.event_name }} event."